import '../models/product.dart';

/// รายการสินค้าทั้งหมดในตู้ ราคาอยู่ในกรอบ 19-89 บาท ตามกลยุทธ์การตั้งราคา
///
/// อยากใส่รูปสินค้า? ไม่ต้องแก้ไฟล์นี้ ไปที่ lib/data/product_images.dart
/// แล้ววาง URL รูปตรง id ของสินค้านั้นได้เลย ไฟล์เดียวจบ
final List<Product> allProducts = [
  // ---------- หมวดกู้ร่าง & แก้แฮงค์ ----------
  Product(
    id: 'r01',
    name: 'Bomi 16.8 Hangover (เจลลี่แก้แฮงค์)',
    emoji: '🧴',
    price: 59,
    category: ProductCategory.recovery,
    initialStock: 12,
  ),
  Product(
    id: 'r02',
    name: 'Berocca Performance (วิตามินเม็ดฟู่)',
    emoji: '💊',
    price: 39,
    category: ProductCategory.recovery,
    initialStock: 15,
  ),
  Product(
    id: 'r03',
    name: 'แคปซูลรางจืด อภัยภูเบศร',
    emoji: '🌿',
    price: 85,
    category: ProductCategory.recovery,
    initialStock: 9,
  ),
  Product(
    id: 'r04',
    name: 'Jele Beautie Gummy (กัมมี่วิตามินซี)',
    emoji: '🍬',
    price: 25,
    category: ProductCategory.recovery,
    initialStock: 14,
  ),
  Product(
    id: 'r05',
    name: 'บ๊วยคืนชีพ Mag Mag',
    emoji: '🍑',
    price: 25,
    category: ProductCategory.recovery,
    initialStock: 3,
  ),
  Product(
    id: 'r06',
    name: 'โจ๊กคัพ คนอร์ รสหมูสับ',
    emoji: '🍲',
    price: 20,
    category: ProductCategory.recovery,
    initialStock: 10,
  ),
  Product(
    id: 'r07',
    name: 'แผ่นแปะลดไข้ Kool Fever',
    emoji: '🧊',
    price: 35,
    category: ProductCategory.recovery,
    initialStock: 11,
  ),
  Product(
    id: 'r08',
    name: 'ผงเกลือแร่ Oreda RO',
    emoji: '🧂',
    price: 10,
    category: ProductCategory.recovery,
    initialStock: 20,
  ),

  // ---------- หมวดแฟชั่น & ร่างกายฉุกเฉิน ----------
  Product(
    id: 'f01',
    name: 'พลาสเตอร์กันรองเท้ากัด 3M Nexcare',
    emoji: '👠',
    price: 45,
    category: ProductCategory.fashion,
    initialStock: 8,
  ),
  Product(
    id: 'f02',
    name: 'เทปกาวติดเสื้อผ้า Watsons Fashion Tape',
    emoji: '🎀',
    price: 89,
    category: ProductCategory.fashion,
    initialStock: 6,
  ),
  Product(
    id: 'f03',
    name: 'Batiste Dry Shampoo ขนาดพกพา (50ml)',
    emoji: '💨',
    price: 129,
    category: ProductCategory.fashion,
    initialStock: 5,
  ),
  Product(
    id: 'f04',
    name: 'ถุงน่อง Cherilon / ถุงเท้าข้อสั้น',
    emoji: '🧦',
    price: 59,
    category: ProductCategory.fashion,
    initialStock: 10,
  ),
  Product(
    id: 'f05',
    name: 'ปากกาขจัดคราบเปื้อน Tide To Go Mini',
    emoji: '🧽',
    price: 150,
    category: ProductCategory.fashion,
    initialStock: 4,
  ),
  Product(
    id: 'f06',
    name: 'กิ๊บดำและยางรัดผม Goody',
    emoji: '💫',
    price: 49,
    category: ProductCategory.fashion,
    initialStock: 12,
  ),

  // ---------- หมวดดับกลิ่น & รีเฟรชความมั่นใจ ----------
  Product(
    id: 's01',
    name: 'สเปรย์ระงับกลิ่นปาก Dentiste Mouth Spray',
    emoji: '👄',
    price: 155,
    category: ProductCategory.freshness,
    initialStock: 9,
  ),
  Product(
    id: 's02',
    name: 'ลูกอม Fisherman\'s Friend',
    emoji: '⚫',
    price: 38,
    category: ProductCategory.freshness,
    initialStock: 18,
  ),
  Product(
    id: 's03',
    name: 'สเปรย์ขจัดกลิ่นบนผ้า Ambi Pur Fabric',
    emoji: '🌬️',
    price: 79,
    category: ProductCategory.freshness,
    initialStock: 7,
  ),
  Product(
    id: 's04',
    name: 'ทิชชู่เปียกเย็นเช็ดตัว Gatsby Ice-Type',
    emoji: '🧻',
    price: 39,
    category: ProductCategory.freshness,
    initialStock: 10,
  ),
  Product(
    id: 's05',
    name: 'กระดาษซับหน้ามัน Gatsby Powdered Oil Clear',
    emoji: '🧻',
    price: 99,
    category: ProductCategory.freshness,
    initialStock: 6,
  ),
  Product(
    id: 's06',
    name: 'น้ำตาเทียมสูตรเย็น Rohto Cool Eye Drops',
    emoji: '👁️',
    price: 199,
    category: ProductCategory.freshness,
    initialStock: 5,
  ),

  // ---------- หมวดอุปกรณ์เอาชีวิตรอด ----------
  Product(
    id: 't01',
    name: 'พัดลมพกพา Jisulife Handheld Fan',
    emoji: '🌀',
    price: 259,
    category: ProductCategory.tech,
    initialStock: 0,
  ),
  Product(
    id: 't02',
    name: 'สายชาร์จ 3-in-1 แบรนด์ Hoco',
    emoji: '🔌',
    price: 119,
    category: ProductCategory.tech,
    initialStock: 6,
  ),
  Product(
    id: 't03',
    name: 'โฟมอุดหูลดเสียง 3M Earplugs (สีส้ม)',
    emoji: '🎧',
    price: 35,
    category: ProductCategory.tech,
    initialStock: 9,
  ),
  Product(
    id: 't04',
    name: 'ซองกันน้ำมือถือ Ocean Pack',
    emoji: '📱',
    price: 89,
    category: ProductCategory.tech,
    initialStock: 4,
  ),
];
